const STATUS_LABELS_PT: Record<string, string> = {
  active: "Ativo",
  inactive: "Inativo",
  trialing: "Período de teste",
  past_due: "Pagamento em atraso",
  pending_approval: "Aguardando aprovação",
  pending_email_verification: "Aguardando verificação de e-mail",
  blocked: "Bloqueado",
  canceled: "Cancelado",
  cancelled: "Cancelado",
  unpaid: "Não pago",
  incomplete: "Incompleto",
  incomplete_expired: "Incompleto e expirado",
  pending: "Pendente",
  processing: "Processando",
  processed: "Processado",
  approved: "Aprovado",
  rejected: "Rejeitado",
  scheduled: "Agendado",
  posting: "Publicando",
  awaiting_container: "Aguardando Instagram",
  posted: "Publicado",
  failed: "Falhou",
  queued: "Na fila",
  analyzing: "Analisando",
  rendering: "Renderizando",
  ready: "Pronto",
  draft: "Rascunho",
  discarded: "Descartado",
  sending: "Enviando",
  sent: "Enviado",
  paused: "Pausado",
  open: "Aberto",
  pending_user: "Aguardando cliente",
  in_progress: "Em andamento",
  resolved: "Resolvido",
  closed: "Fechado",
  complete: "Concluído",
  completed: "Concluído",
  skipped: "Ignorado",
  refunded: "Reembolsado",
  archived: "Arquivado",
  validating: "Validando",
  waiting: "Aguardando",
  pending_payment: "Aguardando pagamento",
  claimed: "Reservado",
  already_processing: "Já está sendo processado",
  duplicate_completed: "Duplicado já concluído",
  completed_with_errors: "Concluído com erros",
  rate_limited: "Aguardando limite de uso",
  deauthorized: "Desautorizado",
  dlq: "Fila de falhas",
  success: "Concluído com sucesso",
  error: "Erro",
  timeout: "Tempo de espera esgotado",
  no_credits: "Sem créditos",
  permanent: "Permanente",
  unknown: "Desconhecido",
};

export function statusLabelPt(status?: string | null): string {
  const original = String(status || "").trim();
  if (!original) return "Não informado";
  const translated = STATUS_LABELS_PT[original.toLowerCase()];
  if (translated) return translated;
  return /^[a-z0-9_]+$/i.test(original) ? "Estado não reconhecido" : original;
}
