// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-topics.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_topics_default = defineTool({
  name: "list_topics",
  title: "Listar pautas",
  description: "Lista as pautas de conte\xFAdo (content_topics) do usu\xE1rio autenticado, com op\xE7\xE3o de filtrar por status.",
  inputSchema: {
    status: z.enum(["draft", "active", "archived"]).optional().describe("Filtrar por status da pauta."),
    limit: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de pautas retornadas (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("content_topics").select("id, title, angle, status, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { topics: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-topic.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_topic_default = defineTool2({
  name: "create_topic",
  title: "Criar pauta",
  description: "Cria uma nova pauta de conte\xFAdo (content_topics) para o usu\xE1rio autenticado.",
  inputSchema: {
    title: z2.string().trim().min(3).max(200).describe("T\xEDtulo da pauta."),
    angle: z2.string().trim().max(500).optional().describe("\xC2ngulo ou abordagem editorial.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, angle }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("content_topics").insert({ user_id: ctx.getUserId(), title, angle: angle ?? null, status: "active" }).select("id, title, angle, status, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Pauta criada: ${data.id}` }],
      structuredContent: { topic: data }
    };
  }
});

// src/lib/mcp/tools/list-scheduled-posts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_scheduled_posts_default = defineTool3({
  name: "list_scheduled_posts",
  title: "Listar posts agendados",
  description: "Lista os posts agendados (scheduled_posts) do usu\xE1rio autenticado, ordenados pela data de publica\xE7\xE3o.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("M\xE1ximo de agendamentos retornados (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("scheduled_posts").select("id, status, scheduled_for, instagram_account_id, news_item_id, created_at").eq("user_id", ctx.getUserId()).order("scheduled_for", { ascending: true }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { scheduled: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var MCP_SUPABASE_PROJECT_REF = "gewnaxrhiyylfizgbqdi";
var MCP_OAUTH_ISSUER = `https://${MCP_SUPABASE_PROJECT_REF}.supabase.co/auth/v1`;
var mcp_default = defineMcp({
  name: "fluxifeed-mcp",
  title: "FluxiFeed MCP",
  version: "0.1.0",
  instructions: "Ferramentas do FluxiFeed. Use list_topics para ver pautas do criador autenticado, create_topic para cadastrar uma nova pauta e list_scheduled_posts para consultar publica\xE7\xF5es agendadas no Instagram.",
  auth: auth.oauth.issuer({
    issuer: MCP_OAUTH_ISSUER,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_topics_default, create_topic_default, list_scheduled_posts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
